server:
  port: 8001

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: 9lpDhfXZaous1shd0Emu7WIZLVfbiK
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.format_sql: true
      hibernate.generate_statistics: false
      hibernate.use_sql_comments: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    generate-ddl: true
    database: postgresql
  mvc:
    converters:
      preferred-json-mapper: gson
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    root: info
